

import json
import os
import argparse

# Indicate the path of the FASTQ generated by the genomic unit
parser= argparse.ArgumentParser(description='Create the .json file for each sample')
parser.add_argument("-d", "--dir", required= True, dest= 'path',
                     help= "Directory from /hpcnfs/techunits/genomics/PublicData/ in which FATSQ are stored"
                    )
parser.add_argument('-o', '--output-p', type=str, required=False, dest='prfopt', default='samples',
                     help='Prefix of the output .json file of the samples')
args = parser.parse_args()

d= args.path
data= {}
for sample in os.listdir(d):
    data[sample[7:]] = {sample : d+sample }

with open(args.prfopt + '.json', 'w') as outfile:
    json.dump(data, outfile)
